### ISSUE TITLE
/api/speaker/{name}/meet 需要 speech_count 的欄位

### ISSUE THREAD

**Issue by codeindex2937** [ronnywang/lysayit-api#1]
目前前端依賴於離線資料

**Comment by ronnywang** [comment]
加好了，請參考 https://lysayit.g0v.ronny.tw/api/speaker/%E9%BB%83%E5%9C%8B%E6%98%8C/meet
請 @codeindex2937 確認看看，沒問題請再幫我關票喔
謝謝
